# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: document.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64ocument.proto\x12\x0f\x44ocumentService\"\"\n\x0e\x45xtractRequest\x12\x10\n\x08\x66ile_url\x18\x01 \x01(\t\"&\n\x0eStreamResponse\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\x32k\n\x08\x44ocument\x12_\n\x17\x45xtractTextFromDocument\x12\x1f.DocumentService.ExtractRequest\x1a\x1f.DocumentService.StreamResponse\"\x00\x30\x01\x42\x15Z\x13\x61pi/document-parserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'document_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\023api/document-parser'
  _globals['_EXTRACTREQUEST']._serialized_start=35
  _globals['_EXTRACTREQUEST']._serialized_end=69
  _globals['_STREAMRESPONSE']._serialized_start=71
  _globals['_STREAMRESPONSE']._serialized_end=109
  _globals['_DOCUMENT']._serialized_start=111
  _globals['_DOCUMENT']._serialized_end=218
# @@protoc_insertion_point(module_scope)
