# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: object-storage.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14object-storage.proto\x12\robjectStorage\"\x18\n\x04Meta\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"8\n\x04\x46ile\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x12!\n\x04meta\x18\x02 \x01(\x0b\x32\x13.objectStorage.Meta\"\"\n\x0eUploadResponse\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t\"\x1e\n\nGetRequest\x12\x10\n\x08\x66ileName\x18\x01 \x01(\t2\x88\x01\n\rObjectStorage\x12>\n\x06Upload\x12\x13.objectStorage.File\x1a\x1d.objectStorage.UploadResponse(\x01\x12\x37\n\x03Get\x12\x19.objectStorage.GetRequest\x1a\x13.objectStorage.File0\x01\x42\x13Z\x11\x61pi/objectstorageb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'object_storage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021api/objectstorage'
  _globals['_META']._serialized_start=39
  _globals['_META']._serialized_end=63
  _globals['_FILE']._serialized_start=65
  _globals['_FILE']._serialized_end=121
  _globals['_UPLOADRESPONSE']._serialized_start=123
  _globals['_UPLOADRESPONSE']._serialized_end=157
  _globals['_GETREQUEST']._serialized_start=159
  _globals['_GETREQUEST']._serialized_end=189
  _globals['_OBJECTSTORAGE']._serialized_start=192
  _globals['_OBJECTSTORAGE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
